apps/reviews/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^books/(?P<book_id>\d+)$', views.book_detail, name='book_detail'),
    url(r'^books/(?P<book_id>\d+)/add_review$', views.book_add_review, name='book_add_review'),
    url(r'^books/add$', views.add_book, name='add_book'),
    url(r'^books/(?P<book_id>\d+)/review/(?P<review_id>\d+)/delete$',
        views.review_delete, name='review_delete'),
    url(r'^users/(?P<user_id>\d+)$', views.user_detail, name='user_detail'),
]

book_review/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('apps.login_register.urls', namespace='login_register')),
    url(r'^reviews/', include('apps.reviews.urls', namespace='reviews')),
]

apps/reviews/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone


# Create your models here.
class Author(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    
    def __str__(self):
        name = self.first_name.title() + ' ' + self.last_name.title()
        return name

class Book(models.Model):
    title = models.CharField(max_length=140)
    authors = models.ManyToManyField(Author, related_name='books')

    def __str__(self):
        return self.title
    

class Review(models.Model):
    rating = models.PositiveIntegerField(default=5, 
                                         validators=(MinValueValidator(1),
                                                     MaxValueValidator(5))
                                        )
    comment = models.TextField(max_length=140)
    user = models.ForeignKey(User, related_name='reviews')
    book = models.ForeignKey(Book, related_name='reviews')
    created_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.comment
    
    def update(self):
        self.update_date = timezone.now
        self.save()

apps/reviews/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model, login, logout
from .models import *


User = get_user_model()


class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('title',)


class AuthorForm(forms.ModelForm):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)

    class Meta:
        model = Author
        fields = ('first_name', 'last_name')
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'first name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'last name'})
        }


class SelectAuthorForm(forms.Form):
    choose_author = forms.ModelChoiceField(queryset=Author.objects.all().order_by('first_name'),
                                           label='Select an author',
                                           required=False)


class ReviewForm(forms.ModelForm):
    rating = forms.ChoiceField(choices=[(x, x) for x in range(1, 6)])

    class Meta:
        model = Review
        fields = ('comment', 'rating')
        widgets = {
            'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'})
        }

apps/reviews/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *


# Create your views here.
def index(request):
    all_reviews = Review.objects.all().order_by('-created_date')[:5]
    books_with_reviews = Book.objects.exclude(reviews__isnull=True)
    context = {
        'all_reviews': all_reviews,
        'books_with_reviews': books_with_reviews,
    }
    return render(request, 'reviews/index.html', context)


def book_detail(request, book_id):
    book_query = get_object_or_404(Book, pk=book_id)
    review_form = ReviewForm(request.POST or None)
    context = {
        'book_query': book_query,
        'book_id': book_id,
        'review_form': review_form,
    }
    return render(request, 'reviews/book_detail.html', context)


@login_required(login_url='/')
def book_add_review(request, book_id):
    review_form = ReviewForm(request.POST or None)
    if review_form.is_valid():
        book_query = Book.objects.get(id=book_id)
        new_review = review_form.save(commit=False)
        new_review.user = get_object_or_404(User, pk=request.user.id)
        new_review.book = book_query
        new_review.save()
        return redirect('reviews:book_detail', book_id=book_id)


@login_required(login_url='/')
def add_book(request):
    book_form = BookForm(request.POST or None)
    select_author_form = SelectAuthorForm(request.POST or None)
    create_author_form = AuthorForm(request.POST or None)
    review_form = ReviewForm(request.POST or None)
    context = {
        'book_form': book_form,
        'select_author_form': select_author_form,
        'create_author_form': create_author_form,
        'review_form': review_form,
    }
    if book_form.is_valid() and review_form.is_valid():
        # check if book exists
        new_book = book_form.save(commit=False)
        try:
            book_query = Book.objects.get(title__iexact=new_book.title)
        except Book.DoesNotExist:
            book_form.save()
            book_query = Book.objects.get(title__iexact=new_book.title)

        # query author to add to the new book
        # either select or create and author
        if select_author_form.has_changed() and select_author_form.is_valid() and not create_author_form.has_changed():
            author_query = select_author_form.cleaned_data.get('choose_author')
        elif create_author_form.has_changed() and create_author_form.is_valid() and not select_author_form.has_changed():
            first_name = create_author_form.cleaned_data.get('first_name')
            last_name = create_author_form.cleaned_data.get('last_name')
            # check if entered author exists
            if Author.objects.filter(first_name__iexact=first_name).filter(last_name__iexact=last_name):
                messages.error(request, 'Author exists, please select from the list.')
                return redirect('reviews:add_book')
            else:
                author_query = Author.objects.create(first_name=first_name, last_name=last_name)
        else:
            messages.error(request, 'You can either select or create an author.')
            return redirect('reviews:add_book')

        # add author to book
        book_query.authors.add(author_query)
        
        # add review
        new_review = review_form.save(commit=False)
        new_review.user = get_object_or_404(User, pk=request.user.id)
        new_review.book = book_query
        new_review.save()

        book_id = book_query.id
        return redirect('reviews:book_detail', book_id=book_id)
    return render(request, 'reviews/add_new.html', context)


@login_required(login_url='/')
def user_detail(request, user_id):
    user_query = get_object_or_404(User, id=user_id)
    reviews_query = user_query.reviews.all()
    reviews_query_count = reviews_query.count()
    context = {
        'user_query': user_query,
        'reviews_query': reviews_query,
        'reviews_query_count': reviews_query_count,
    }
    return render(request, 'reviews/user_detail.html', context)


@login_required(login_url='/')
def review_delete(request, book_id, review_id):
    Review.objects.get(pk=review_id).delete()
    return redirect('reviews:book_detail', book_id=book_id)

apps/reviews/templates/reviews/add_new.html
{% extends 'reviews/base.html' %}

{% block content %}

{% if messages %} {% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
    <p>{{ message }}</p>
</div>
{% endfor %} {% endif %}

<form action="{% url 'reviews:add_book' %}" method="POST">
    {% csrf_token %}
    {{ book_form.as_p }}
    {{ select_author_form.as_p }}
    <fieldset>
        <h5>Or create an author</h5>
        {{ create_author_form.as_p }}
        {{ review_form.as_p }}
    </fieldset>
    <input type="submit" class="btn" value="Submit" />
</form>

{% endblock %}

apps/reviews/templates/reviews/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Book Review{% endblock %}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- add bootstrap -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <!-- add customise stylesheet -->
        {% load static %}
        {% block stylesheet %}
        <link href="{% static 'login_register/css/my_style.css' %}" rel="stylesheet">
        {% endblock %}
    </head>
    <body>
        <div class="navbar navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <!-- the hamburger menu-->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <!-- the hamburger menu-->
                    </button>
                    <a class="navbar-brand" href="{% url 'reviews:index' %}">Book Review</a>
                </div>
                 {% block navbar %}
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <!-- <li><a href="/"></a></li> -->
                            <li><a href="/logout">Logout</a></li>
                        </ul>
                    </div>
                {% endblock %}
            </div>
        </div>
        <main>
            
        
        <div class="content container">
            <div class="row">
                
                    {% block content %}
                    {% endblock %}
                
            </div>
        </div>
    </main>

        <!-- Latest compiled and minified JavaScript -->
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        {% block javascript %}
        
        {% endblock %}
        
    </body>
</html>

apps/reviews/templates/reviews/book_detail.html
{% extends 'reviews/base.html' %}

{% block content %}
    <h2>{{ book_query.title.title }}</h2>
    <form action="{% url 'reviews:book_add_review' book_id=book_query.id %}" method="POST">
        {% csrf_token %}
        {{ review_form.as_p }}
        <input type="submit" class="btn" value="Submit" />
    </form>
    <h3>Reviews</h3>
    {% for review in book_query.reviews.all %}
    <ul>
        <li>
            {% if review.rating == 1 %}
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            <span class="glyphicon glyphicon-star-empty"></span> {% elif review.rating == 2 %}
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            <span class="glyphicon glyphicon-star-empty"></span> {% elif review.rating == 3 %}
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            <span class="glyphicon glyphicon-star-empty"></span> {% elif review.rating == 4 %}
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star-empty"></span> {% else %}
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span> {% endif %}
        </li>
        <li>
            <a href="{% url 'reviews:user_detail' user_id=review.user.id %}">
                {{ review.user.first_name.title }}
            </a> says:
            <span> {{ review.comment }}</span>
            {% if request.user.id == review.user.id %}
                <button><a href="{% url 'reviews:review_delete' book_id=book_id review_id=review.pk %}">Delete Review</a></button>
            {% endif %}
        </li>
        <li>Posted on: {{ review.created_date }}</li>
    </ul>
    {% endfor %}

{% endblock %}

apps/reviews/templates/reviews/index.html
{% extends 'reviews/base.html' %}

{% block content %}
    {% if request.user.is_authenticated %}
        <h2>Welcome {{ request.user.first_name.title }}!</h2>
    {% else %}
        <h2><a href="{% url 'login_register:index' %}">Please login here.</a></h2>
    {% endif %}

    <h2>Recent Book Reviews</h2>
    <h3>
        <a href="{% url 'reviews:add_book' %}">Add a book and review!</a>
    </h3>

    {% for review in all_reviews %}
    <ul>
        <li>
            <a href="{% url 'reviews:book_detail' book_id=review.book.id %}">
                {{ review.book.title }}
            </a>
        </li>
        <li>
            {% if review.rating == 1 %}
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            {% elif review.rating == 2 %}
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            {% elif review.rating == 3 %}
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            {% elif review.rating == 4 %}
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            {% else %}
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            {% endif %}
        </li>
        <li>
            <a href="{% url 'reviews:user_detail' user_id=review.user.id %}">
                {{ review.user.first_name.title }}
            </a> 
            says:
            <span> {{ review.comment }}</span>
        </li>
        <li>Posted on: {{ review.created_date }}</li>
    </ul>
    {% endfor %}

    <section>
        <h3>Other books with reviews</h3>
        <ul>
            {% for book in books_with_reviews %}
            <li><a href="{% url 'reviews:book_detail' book_id=book.id %}">{{ book.title.title }}</a></li>
            {% endfor %}
        </ul>
    </section>



{% endblock %}

apps/reviews/templates/reviews/user_detail.html
{% extends 'reviews/base.html' %}

{% block content %}
    <h2>Hi, I am {{ user_query.username }}!</h2>
    <h3>Name: {{ user_query.first_name.title }} {{ user_query.last_name.title }}</h3>
    <h3>Email: {{ user_query.email }}</h3>
    <h3>Total reviews: {{ reviews_query_count }}</h3>

    <h2>Posted reviews on the following books</h2>
    <ul>
        {% for review in reviews_query %}
            <li>
                <a href="{% url 'reviews:book_detail' book_id=review.book.id %}">
                    {{ review.book.title.title }}
                </a>
            </li>
        {% endfor %}
    </ul>



{% endblock %}